Repository kcl-lang/kcl-go, pull requests merged in 2023-04, with the labels that each got.

#94 fix: Broken pipe in FormatPath
  pkg/kclvm_runtime/proc.go
  pkg/tools/format/format_test.go
Labels: bug

#97 feat(pkg/tools/gen): generate kcl schema from go struct
  pkg/tools/gen/genkcl.go
  pkg/tools/gen/genkcl_test.go
  pkg/tools/gen/gotypes.go
  pkg/tools/gen/gotypes_test.go
  pkg/tools/gen/testdata/genkcldata.go
Labels: gen

#99 chore: update readme and bump kclvm abi version to 0.4.6
  .gitignore
  README.md
  cmds/kcl-go/command/cmd_main.go
  cmds/kcl-go/command/cmd_setup_kclvm.go
  scripts/doc.go
  scripts/examples_test.go
  scripts/kclvm.go
  scripts/kclvm_asset_helper.go
  scripts/util_unzip.go
Labels: release
