Repository kcl-lang/kcl-go, pull requests merged in 2023-06, with the labels that each got.

#111 refactor: kcl lib install add add file locks
  .github/workflows/main_darwin.yml
  .github/workflows/main_linux.yml
  .github/workflows/main_windows.yml
  go.mod
  go.sum
  pkg/kclvm_runtime/kclvm.go
  pkg/path/lazypath_unix.go
  pkg/path/lib.go
Labels: release

#113 Feat: add api 'WithExternalPkg'.
  go.mod
  go.sum
  kclvm.go
  kclvm_test.go
  pkg/kcl/opt.go
  pkg/path/lazypath_windows.go
  pkg/spec/gpyrpc/gpyrpc.pb.go
  pkg/spec/gpyrpc/gpyrpc.proto
  testdata/import-external/main.k
  testdata_external/external_1/kcl.mod
  testdata_external/external_1/main.k
  testdata_external/external_2/kcl.mod
  testdata_external/external_2/main.k
Labels: enhancement

#115 fix: add 'manifests' function in builtin pkgs.
  pkg/tools/list/list_test.go
  pkg/tools/list/utils.go
  testdata_import_builtin/entry/main.k
  testdata_import_builtin/kcl.mod
  testdata_import_builtin/sub/main.k
Labels: bug

#117 fix: add 'RunWithOpts' to avoid input the kfile twice.
  pkg/kcl/api.go
  pkg/kcl/api_test.go
Labels: bug

#118 chore: bump kcl version to v0.5.0-alpha.4.
  go.mod
  go.sum
  scripts/kclvm.go
Labels: release
