Repository kcl-lang/kcl-go, pull requests merged in 2024-03, with the labels that each got.

#252 Add all `service.KclvmService` methods to `NativeServiceClient`
  pkg/native/client.go
Labels: api

#259 feat: disable shared lib install at the code level
  pkg/env/env.go
  pkg/native/loader.go
  pkg/path/lazypath.go
  pkg/runtime/init.go
  pkg/runtime/kclvm.go
  pkg/utils/utils.go
Labels: enhancement

#262 test: add native parse file API test
  pkg/native/client_test.go
Labels: test
